arangodb:
  dbName: TUThyeakkvs3t80rlwqg9tnipi
  edge_col: entity-feature-value
  entity_col: entity
  feature_value_col: feature-value
  graph_name: feature_store_graph
  hostname: tutorials.arangodb.cloud
  password: TUTiupac2s53i2kmnfuo5foq
  port: 8529
  protocol: https
  replication_factor: 3
  username: TUTfprz11d3r4omnmbrvidia
